name: my-app

# Kubernetes namespace to install into (can be overridden)
namespace: stnvivanco92-dev

replicaCount: 1

container:
  image: "savivancofi/cursosv2"
  tag: "34"
  port: 3000

service:
  type: ClusterIP
  port: 4000

resources:
  requests:
    cpu: "500m"
    memory: "800Mi"
  limits:
    cpu: "1000m"
    memory: "1500Mi"

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75

configmap:
  database: "192.168.1.1"

secret:
  # plain text password; template will base64-encode when placing into `data:`
  password: "hola"